# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting_robot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_robot_setting(object):
    def setupUi(self, robot_setting):
        robot_setting.setObjectName("robot_setting")
        robot_setting.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(robot_setting)
        self.pushButton.setGeometry(QtCore.QRect(130, 230, 141, 31))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(robot_setting)
        self.widget.setGeometry(QtCore.QRect(80, 30, 244, 161))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)

        self.retranslateUi(robot_setting)
        QtCore.QMetaObject.connectSlotsByName(robot_setting)

    def retranslateUi(self, robot_setting):
        _translate = QtCore.QCoreApplication.translate
        robot_setting.setWindowTitle(_translate("robot_setting", "Robot Settings"))
        self.pushButton.setText(_translate("robot_setting", "Save Values"))
        self.label.setText(_translate("robot_setting", "IPV4 Address:"))
        self.lineEdit.setText(_translate("robot_setting", "192.168.1.24"))
        self.label_2.setText(_translate("robot_setting", "Port:"))
        self.lineEdit_2.setText(_translate("robot_setting", "30003"))
        self.label_3.setText(_translate("robot_setting", "Bytes:"))
        self.lineEdit_3.setText(_translate("robot_setting", "1116"))
